vich_uploader:
    db_driver: orm

    mappings:
       property_image:
          uri_prefix: /images/drums
          upload_destination: '%kernel.project_dir%/public/images/drums'
          namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
